
l:
	aws sqs list-queues \
		--endpoint-url http://localhost:4566

r:
	aws sqs receive-message --queue-url http://sqs.ap-northeast-1.localhost.localstack.cloud:4566/000000000000/celery \
		--endpoint-url http://localhost:4566

